### ISSUE TITLE
App crashing at the very beginning.

### ISSUE THREAD

**Issue by legildas** [saisilinus/node-express-mongoose-typescript-boilerplate#32]
**Describe the bug**
The app crashes when I start it.

**To Reproduce**
1. `npx create-nodejs-ts-app back`
2. `cd back`
3. `yarn dev`
4. See error (screenshot)

**Expected behavior**
The app should work as expected.

**Screenshots**
<img width="1267" alt="Capture d’écran 2022-11-23 à 17 10 34" src="https://user-images.githubusercontent.com/6241539/203594615-f770710d-8e9d-4b99-b0f3-965271d2a407.png">

**Desktop :**
 - OS: MacOS Monterey (12.3)

**Additional context**
This is the same behaviour with `yarn start`. I also tried to `yarn compile` first but it didn't change anything.

Thanks for your help !

**Comment by saisilinus** [comment]
Hey, you are getting the error because you are using Node.js v19.0.1. To enable imports without file extensions, e.g. `import app from './app'`, I used the flag `--es-module-specifier-resolution=node` when running the app. However, this has been deprecated in the release of [Node.js v19](https://nodejs.org/en/blog/announcements/v19-release-announce/#custom-esm-resolution-adjustments) in favor of [custom loaders](https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader). You can check out the PR [here](https://github.com/nodejs/node/pull/44859).

I would like to support the previous Node.js versions as well as v19 and will work on this soon. I will appreciate any help on the issue.

I advise you to use a different version of Node.js for now - Node.js 14 to 18 should be okay

**Comment by gsaynac** [comment]
Indeed ! It's now working with the lts version of Node.js (18.12.1). Thanks a lot !

**Comment by saisilinus** [comment]
Sure :wink:
