### ISSUE TITLE
child route name getting fetched by objectId validation along with customerId

### ISSUE THREAD

**Issue by tamirazrab** [saisilinus/node-express-mongoose-typescript-boilerplate#43]
**Describe the bug**
`router
  .route('/explore/:customerId')
  .get(validate(productValidation.exploreCrafts), productController.exploreCrafts)` 
  
 Here's my route and here's what I'm getting in objectId validation value:
 https://i.imgur.com/aUvfj0u.png

**Expected behavior**
Is there any way I can still use route as it is and only params gets picked up?

**Comment by saisilinus** [comment]
Hey. I can't view the [image](https://i.imgur.com/aUvfj0u.png). Check your url and make sure it works

**Comment by tamirazrab** [comment]
Must've been private here's the URL https://imgur.com/a/nRe4JDP

**Comment by saisilinus** [comment]
Your customerId is not a valid mongo id

**Comment by tamirazrab** [comment]
If you see, I'm printing the value of objectId validator that I'm getting, and I can also see 'explore' there first, and then my customerId comes. My initial reason to create an issue was why 'explore' is getting there, and how can I prevent this. Removing 'explore' from the route worked.

**Comment by saisilinus** [comment]
It seems like this is a routing issue. Please check how Express handles
dynamic routes. I don't have enough information to help you here. Why are
you calling '/product/explore/:customerId' when you have defined the route
as '/explore/:customerId'?

**Comment by saisilinus** [comment]
You don't have to add the `/explore`, `/delete-file`, or `/upload-product-file` parts. You can just have the main route as `/product` then have the child routes as `/:customerId` and differentiate them using the `GET`, `PUT`, and `DELETE` methods.

When you have a dynamic child route such as `/:customerId` then you add a sibling route as `/explore/:customerId`, Express will get confused as it is expecting a param at `/:customerId` but sometimes its getting `/explore/:customerId` and it doesn't parse the values consistently or at least like you would expect. Express sees `/product/some-mongo-id` and `/product/explore/some-mongo-id` as the same thing and parses `/explore/some-mongo-id` as `/some-mongo-id`. 

If you need to add separate child routes with routes such as `/explore` and `/delete-file` you can't include dynamic routes so that Express is aware that you only have static routes and they all map to different paths.

Alternatively you can always create additional parent routes as there is no limit.

You can check out additional documentation [here](https://expressjs.com/en/guide/routing.html)

**Comment by tamirazrab** [comment]
I see, didn't expected that behavior, well thanks for clarification I thought it had to do how route designed but seems like I got a lot of refactoring to do.
