### ISSUE TITLE
Send Email Authentication Email send issues or  unclear about this.

### ISSUE THREAD

**Issue by Tarikul01** [saisilinus/node-express-mongoose-typescript-boilerplate#58]
Here i see  you use this routes
router.post('/send-verification-email', auth(), authController.sendVerificationEmail);

but I have some question. this is used where the    didn't active their account and token   validate date expires then need to send token again  . 

But you use auth(). how it work? i think passport use token and check the user is authenticate or not. but here I see you use.  how the user get token without login or  validate their account?

**Comment by saisilinus** [comment]
The `/send-verification-email` route is used when a user wants to verify their email. The user has to be logged in for their email to be retrieved; that's why there is an `auth()` middleware. The access token is just used to confirm the user is logged in. The user will then get an email with a `verify-email` token which will verify their email once clicked.

**Comment by Tarikul01** [comment]
i see you sent a verify-email and sent a token using params.
how it works and how I can get this token. I am not clear about this process.

first, when the user completes registration he gets a verifying email for email verification,  then he clicks the link and token add /verify-email?token=token, when he clicks this link he verifies this email. but how work /send-verification-email?

**Comment by saisilinus** [comment]
Please go through the code and you will get the answers to your questions. The 'Issues' section is not for getting explanation of how the code works; it's for reporting a problem with the code.

That said, you get the token from the email as I said in my previous comment.
